"use client";

import { useEffect, useState } from "react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { Loader2 } from "lucide-react";
import type { CompanyInsights } from "@/app/api/insights/route";

interface Props {
  companyName: string | null;
  onClose: () => void;
}

export function CompanyInsightsSheet({ companyName, onClose }: Props) {
  const [insights, setInsights] = useState<CompanyInsights | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!companyName) return;
    setInsights(null);
    setError(null);
    setLoading(true);

    fetch("/api/insights", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ company_name: companyName }),
    })
      .then((r) => r.json())
      .then((r) => {
        if (r.data) setInsights(r.data as CompanyInsights);
        else setError(r.error ?? "Failed to load insights");
      })
      .catch(() => setError("Network error"))
      .finally(() => setLoading(false));
  }, [companyName]);

  return (
    <Sheet open={!!companyName} onOpenChange={(open) => { if (!open) onClose(); }}>
      <SheetContent className="w-[420px] sm:w-[480px] overflow-y-auto">
        <SheetHeader>
          <SheetTitle className="text-base font-semibold leading-snug pr-6">
            {companyName}
          </SheetTitle>
          <p className="text-xs text-muted-foreground">AI-generated analysis · Gemini 2.0 Flash</p>
        </SheetHeader>

        <div className="mt-6 space-y-5">
          {loading && (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              Analyzing…
            </div>
          )}

          {error && (
            <p className="text-sm text-destructive">{error}</p>
          )}

          {insights && (
            <>
              {/* Tags row */}
              <div className="flex flex-wrap gap-2">
                {insights.sector && insights.sector !== "Unknown" && (
                  <Badge variant="default" className="text-xs">{insights.sector}</Badge>
                )}
                {insights.geography && insights.geography !== "Unknown" && (
                  <Badge variant="default" className="text-xs">{insights.geography}</Badge>
                )}
                {insights.fundingStage && insights.fundingStage !== "Unknown" && (
                  <Badge variant="default" className="text-xs">{insights.fundingStage}</Badge>
                )}
              </div>

              {/* Description */}
              {insights.description && (
                <section>
                  <h3 className="text-xs font-medium uppercase tracking-wide text-muted-foreground mb-1">
                    What they do
                  </h3>
                  <p className="text-sm leading-relaxed">{insights.description}</p>
                </section>
              )}

              {/* Market opportunity */}
              {insights.marketOpportunity && (
                <section>
                  <h3 className="text-xs font-medium uppercase tracking-wide text-muted-foreground mb-1">
                    Market opportunity
                  </h3>
                  <p className="text-sm leading-relaxed">{insights.marketOpportunity}</p>
                </section>
              )}

              {/* Key considerations */}
              {insights.considerations?.length > 0 && (
                <section>
                  <h3 className="text-xs font-medium uppercase tracking-wide text-muted-foreground mb-2">
                    Key considerations
                  </h3>
                  <ul className="space-y-1.5">
                    {insights.considerations.map((c, i) => (
                      <li key={i} className="flex gap-2 text-sm">
                        <span className="text-muted-foreground mt-0.5">·</span>
                        <span>{c}</span>
                      </li>
                    ))}
                  </ul>
                </section>
              )}

              <p className="text-[11px] text-muted-foreground border-t pt-4">
                Analysis generated by AI and may not reflect current information. Verify independently before making investment decisions.
              </p>
            </>
          )}
        </div>
      </SheetContent>
    </Sheet>
  );
}
